version: "3.5"

services:
    postgres:
        container_name: postgres_cda_archi
        image: postgres:16.2
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-ski}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ski}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5435:5432"
        networks:
            - postgres
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@ski.io}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: "False"
        volumes:
            - pgadmin:/var/lib/pgadmin

        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - postgres
        restart: unless-stopped

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
    pgadmin:
